[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_anchor = "5mTeXxoS5W3VZB1MFp9x4revzgMFentyansfxNGVbvwH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
