[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault_anchor = "DZA294uXy8zdcW8FZEXYCHMJ6Z1NriEuT7D6V5S1vjQH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
